# Generated by Django 3.2.25 on 2024-09-29 17:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
